workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        provisioning_profiles:
          - profile: falcon_Provisioning  # Ensure this matches the profile name
        certificates:
          - certificate: distribution_certificate_2  # Ensure this matches the certificate name
        bundle_identifier: com.falconelearning2024.falcon
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Install pods
        script: |
          find ios -name "Podfile" -execdir pod install \;

      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1)) \
            --export-options-plist=export_options.plist  # Path updated to root of project

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: apple_id
        apple_id: "ahmedrashad6655ss@gmail.com"
        password: "falcon2024"
        submit_to_testflight: true  # Set to true to publish on TestFlight
        submit_to_app_store: true   # Set to true to submit directly to App Store
        release_type: SCHEDULED

















#    scripts:
#      - name: Install Flutter dependencies
#        script: flutter packages pub get
#
#      - name: Generate Podfile if missing
#        script: |
#          if [ ! -f ios/Podfile ]; then
#            flutter build ios
#          fi
#
#      - name: Update CocoaPods repository
#        script: cd ios && pod repo update && cd ..
#
#      - name: Set iOS deployment target to 12.0+
#        script: |
#          if [ -f ios/Podfile ]; then
#            sed -i '' 's/PLATFORM_VERSION = 9.0/PLATFORM_VERSION = 12.0/' ios/Podfile
#            cd ios && pod install && cd ..
#          fi
#
#      - name: Build iOS release with codesigning
#        script: flutter build ios --release